// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet.proto

package com.isuru.wallet.service;

/**
 * <pre>
 * Balance resource for particular account.
 * </pre>
 *
 * Protobuf type {@code wallet.AccountBalance}
 */
public  final class AccountBalance extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.AccountBalance)
    AccountBalanceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountBalance.newBuilder() to construct.
  private AccountBalance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountBalance() {
    userId_ = 0;
    accountId_ = 0;
    userEmail_ = "";
    balance_ = 0D;
    currency_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccountBalance(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            userId_ = input.readInt32();
            break;
          }
          case 16: {

            accountId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userEmail_ = s;
            break;
          }
          case 33: {

            balance_ = input.readDouble();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            currency_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.isuru.wallet.service.Wallet.internal_static_wallet_AccountBalance_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.isuru.wallet.service.Wallet.internal_static_wallet_AccountBalance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.isuru.wallet.service.AccountBalance.class, com.isuru.wallet.service.AccountBalance.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private int userId_;
  /**
   * <code>int32 user_id = 1;</code>
   */
  public int getUserId() {
    return userId_;
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 2;
  private int accountId_;
  /**
   * <code>int32 account_id = 2;</code>
   */
  public int getAccountId() {
    return accountId_;
  }

  public static final int USER_EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object userEmail_;
  /**
   * <code>string user_email = 3;</code>
   */
  public java.lang.String getUserEmail() {
    java.lang.Object ref = userEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string user_email = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserEmailBytes() {
    java.lang.Object ref = userEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BALANCE_FIELD_NUMBER = 4;
  private double balance_;
  /**
   * <code>double balance = 4;</code>
   */
  public double getBalance() {
    return balance_;
  }

  public static final int CURRENCY_FIELD_NUMBER = 5;
  private int currency_;
  /**
   * <code>.wallet.CurrencyType currency = 5;</code>
   */
  public int getCurrencyValue() {
    return currency_;
  }
  /**
   * <code>.wallet.CurrencyType currency = 5;</code>
   */
  public com.isuru.wallet.service.CurrencyType getCurrency() {
    com.isuru.wallet.service.CurrencyType result = com.isuru.wallet.service.CurrencyType.valueOf(currency_);
    return result == null ? com.isuru.wallet.service.CurrencyType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0) {
      output.writeInt32(1, userId_);
    }
    if (accountId_ != 0) {
      output.writeInt32(2, accountId_);
    }
    if (!getUserEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userEmail_);
    }
    if (balance_ != 0D) {
      output.writeDouble(4, balance_);
    }
    if (currency_ != com.isuru.wallet.service.CurrencyType.EUR.getNumber()) {
      output.writeEnum(5, currency_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, userId_);
    }
    if (accountId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, accountId_);
    }
    if (!getUserEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userEmail_);
    }
    if (balance_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, balance_);
    }
    if (currency_ != com.isuru.wallet.service.CurrencyType.EUR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, currency_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.isuru.wallet.service.AccountBalance)) {
      return super.equals(obj);
    }
    com.isuru.wallet.service.AccountBalance other = (com.isuru.wallet.service.AccountBalance) obj;

    boolean result = true;
    result = result && (getUserId()
        == other.getUserId());
    result = result && (getAccountId()
        == other.getAccountId());
    result = result && getUserEmail()
        .equals(other.getUserEmail());
    result = result && (
        java.lang.Double.doubleToLongBits(getBalance())
        == java.lang.Double.doubleToLongBits(
            other.getBalance()));
    result = result && currency_ == other.currency_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId();
    hash = (37 * hash) + USER_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getUserEmail().hashCode();
    hash = (37 * hash) + BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBalance()));
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + currency_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.isuru.wallet.service.AccountBalance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.isuru.wallet.service.AccountBalance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.isuru.wallet.service.AccountBalance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.isuru.wallet.service.AccountBalance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.isuru.wallet.service.AccountBalance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Balance resource for particular account.
   * </pre>
   *
   * Protobuf type {@code wallet.AccountBalance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.AccountBalance)
      com.isuru.wallet.service.AccountBalanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.isuru.wallet.service.Wallet.internal_static_wallet_AccountBalance_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.isuru.wallet.service.Wallet.internal_static_wallet_AccountBalance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.isuru.wallet.service.AccountBalance.class, com.isuru.wallet.service.AccountBalance.Builder.class);
    }

    // Construct using com.isuru.wallet.service.AccountBalance.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      userId_ = 0;

      accountId_ = 0;

      userEmail_ = "";

      balance_ = 0D;

      currency_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.isuru.wallet.service.Wallet.internal_static_wallet_AccountBalance_descriptor;
    }

    public com.isuru.wallet.service.AccountBalance getDefaultInstanceForType() {
      return com.isuru.wallet.service.AccountBalance.getDefaultInstance();
    }

    public com.isuru.wallet.service.AccountBalance build() {
      com.isuru.wallet.service.AccountBalance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.isuru.wallet.service.AccountBalance buildPartial() {
      com.isuru.wallet.service.AccountBalance result = new com.isuru.wallet.service.AccountBalance(this);
      result.userId_ = userId_;
      result.accountId_ = accountId_;
      result.userEmail_ = userEmail_;
      result.balance_ = balance_;
      result.currency_ = currency_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.isuru.wallet.service.AccountBalance) {
        return mergeFrom((com.isuru.wallet.service.AccountBalance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.isuru.wallet.service.AccountBalance other) {
      if (other == com.isuru.wallet.service.AccountBalance.getDefaultInstance()) return this;
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (other.getAccountId() != 0) {
        setAccountId(other.getAccountId());
      }
      if (!other.getUserEmail().isEmpty()) {
        userEmail_ = other.userEmail_;
        onChanged();
      }
      if (other.getBalance() != 0D) {
        setBalance(other.getBalance());
      }
      if (other.currency_ != 0) {
        setCurrencyValue(other.getCurrencyValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.isuru.wallet.service.AccountBalance parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.isuru.wallet.service.AccountBalance) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 user_id = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 user_id = 1;</code>
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 user_id = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private int accountId_ ;
    /**
     * <code>int32 account_id = 2;</code>
     */
    public int getAccountId() {
      return accountId_;
    }
    /**
     * <code>int32 account_id = 2;</code>
     */
    public Builder setAccountId(int value) {
      
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 account_id = 2;</code>
     */
    public Builder clearAccountId() {
      
      accountId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object userEmail_ = "";
    /**
     * <code>string user_email = 3;</code>
     */
    public java.lang.String getUserEmail() {
      java.lang.Object ref = userEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserEmailBytes() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_email = 3;</code>
     */
    public Builder setUserEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_email = 3;</code>
     */
    public Builder clearUserEmail() {
      
      userEmail_ = getDefaultInstance().getUserEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string user_email = 3;</code>
     */
    public Builder setUserEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userEmail_ = value;
      onChanged();
      return this;
    }

    private double balance_ ;
    /**
     * <code>double balance = 4;</code>
     */
    public double getBalance() {
      return balance_;
    }
    /**
     * <code>double balance = 4;</code>
     */
    public Builder setBalance(double value) {
      
      balance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double balance = 4;</code>
     */
    public Builder clearBalance() {
      
      balance_ = 0D;
      onChanged();
      return this;
    }

    private int currency_ = 0;
    /**
     * <code>.wallet.CurrencyType currency = 5;</code>
     */
    public int getCurrencyValue() {
      return currency_;
    }
    /**
     * <code>.wallet.CurrencyType currency = 5;</code>
     */
    public Builder setCurrencyValue(int value) {
      currency_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.CurrencyType currency = 5;</code>
     */
    public com.isuru.wallet.service.CurrencyType getCurrency() {
      com.isuru.wallet.service.CurrencyType result = com.isuru.wallet.service.CurrencyType.valueOf(currency_);
      return result == null ? com.isuru.wallet.service.CurrencyType.UNRECOGNIZED : result;
    }
    /**
     * <code>.wallet.CurrencyType currency = 5;</code>
     */
    public Builder setCurrency(com.isuru.wallet.service.CurrencyType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      currency_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.CurrencyType currency = 5;</code>
     */
    public Builder clearCurrency() {
      
      currency_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.AccountBalance)
  }

  // @@protoc_insertion_point(class_scope:wallet.AccountBalance)
  private static final com.isuru.wallet.service.AccountBalance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.isuru.wallet.service.AccountBalance();
  }

  public static com.isuru.wallet.service.AccountBalance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountBalance>
      PARSER = new com.google.protobuf.AbstractParser<AccountBalance>() {
    public AccountBalance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AccountBalance(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccountBalance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountBalance> getParserForType() {
    return PARSER;
  }

  public com.isuru.wallet.service.AccountBalance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

