// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet.proto

package com.isuru.wallet.service;

/**
 * <pre>
 * </pre>
 *
 * Protobuf type {@code wallet.DepositRequest}
 */
public  final class DepositRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.DepositRequest)
    DepositRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DepositRequest.newBuilder() to construct.
  private DepositRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DepositRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DepositRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.isuru.wallet.service.Transaction.Builder subBuilder = null;
            if (deposit_ != null) {
              subBuilder = deposit_.toBuilder();
            }
            deposit_ = input.readMessage(com.isuru.wallet.service.Transaction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deposit_);
              deposit_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.isuru.wallet.service.Wallet.internal_static_wallet_DepositRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.isuru.wallet.service.Wallet.internal_static_wallet_DepositRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.isuru.wallet.service.DepositRequest.class, com.isuru.wallet.service.DepositRequest.Builder.class);
  }

  public static final int DEPOSIT_FIELD_NUMBER = 1;
  private com.isuru.wallet.service.Transaction deposit_;
  /**
   * <code>.wallet.Transaction deposit = 1;</code>
   */
  public boolean hasDeposit() {
    return deposit_ != null;
  }
  /**
   * <code>.wallet.Transaction deposit = 1;</code>
   */
  public com.isuru.wallet.service.Transaction getDeposit() {
    return deposit_ == null ? com.isuru.wallet.service.Transaction.getDefaultInstance() : deposit_;
  }
  /**
   * <code>.wallet.Transaction deposit = 1;</code>
   */
  public com.isuru.wallet.service.TransactionOrBuilder getDepositOrBuilder() {
    return getDeposit();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (deposit_ != null) {
      output.writeMessage(1, getDeposit());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (deposit_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDeposit());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.isuru.wallet.service.DepositRequest)) {
      return super.equals(obj);
    }
    com.isuru.wallet.service.DepositRequest other = (com.isuru.wallet.service.DepositRequest) obj;

    boolean result = true;
    result = result && (hasDeposit() == other.hasDeposit());
    if (hasDeposit()) {
      result = result && getDeposit()
          .equals(other.getDeposit());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDeposit()) {
      hash = (37 * hash) + DEPOSIT_FIELD_NUMBER;
      hash = (53 * hash) + getDeposit().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.isuru.wallet.service.DepositRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.isuru.wallet.service.DepositRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.isuru.wallet.service.DepositRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.isuru.wallet.service.DepositRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.isuru.wallet.service.DepositRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code wallet.DepositRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.DepositRequest)
      com.isuru.wallet.service.DepositRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.isuru.wallet.service.Wallet.internal_static_wallet_DepositRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.isuru.wallet.service.Wallet.internal_static_wallet_DepositRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.isuru.wallet.service.DepositRequest.class, com.isuru.wallet.service.DepositRequest.Builder.class);
    }

    // Construct using com.isuru.wallet.service.DepositRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (depositBuilder_ == null) {
        deposit_ = null;
      } else {
        deposit_ = null;
        depositBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.isuru.wallet.service.Wallet.internal_static_wallet_DepositRequest_descriptor;
    }

    public com.isuru.wallet.service.DepositRequest getDefaultInstanceForType() {
      return com.isuru.wallet.service.DepositRequest.getDefaultInstance();
    }

    public com.isuru.wallet.service.DepositRequest build() {
      com.isuru.wallet.service.DepositRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.isuru.wallet.service.DepositRequest buildPartial() {
      com.isuru.wallet.service.DepositRequest result = new com.isuru.wallet.service.DepositRequest(this);
      if (depositBuilder_ == null) {
        result.deposit_ = deposit_;
      } else {
        result.deposit_ = depositBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.isuru.wallet.service.DepositRequest) {
        return mergeFrom((com.isuru.wallet.service.DepositRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.isuru.wallet.service.DepositRequest other) {
      if (other == com.isuru.wallet.service.DepositRequest.getDefaultInstance()) return this;
      if (other.hasDeposit()) {
        mergeDeposit(other.getDeposit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.isuru.wallet.service.DepositRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.isuru.wallet.service.DepositRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.isuru.wallet.service.Transaction deposit_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.isuru.wallet.service.Transaction, com.isuru.wallet.service.Transaction.Builder, com.isuru.wallet.service.TransactionOrBuilder> depositBuilder_;
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    public boolean hasDeposit() {
      return depositBuilder_ != null || deposit_ != null;
    }
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    public com.isuru.wallet.service.Transaction getDeposit() {
      if (depositBuilder_ == null) {
        return deposit_ == null ? com.isuru.wallet.service.Transaction.getDefaultInstance() : deposit_;
      } else {
        return depositBuilder_.getMessage();
      }
    }
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    public Builder setDeposit(com.isuru.wallet.service.Transaction value) {
      if (depositBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deposit_ = value;
        onChanged();
      } else {
        depositBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    public Builder setDeposit(
        com.isuru.wallet.service.Transaction.Builder builderForValue) {
      if (depositBuilder_ == null) {
        deposit_ = builderForValue.build();
        onChanged();
      } else {
        depositBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    public Builder mergeDeposit(com.isuru.wallet.service.Transaction value) {
      if (depositBuilder_ == null) {
        if (deposit_ != null) {
          deposit_ =
            com.isuru.wallet.service.Transaction.newBuilder(deposit_).mergeFrom(value).buildPartial();
        } else {
          deposit_ = value;
        }
        onChanged();
      } else {
        depositBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    public Builder clearDeposit() {
      if (depositBuilder_ == null) {
        deposit_ = null;
        onChanged();
      } else {
        deposit_ = null;
        depositBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    public com.isuru.wallet.service.Transaction.Builder getDepositBuilder() {
      
      onChanged();
      return getDepositFieldBuilder().getBuilder();
    }
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    public com.isuru.wallet.service.TransactionOrBuilder getDepositOrBuilder() {
      if (depositBuilder_ != null) {
        return depositBuilder_.getMessageOrBuilder();
      } else {
        return deposit_ == null ?
            com.isuru.wallet.service.Transaction.getDefaultInstance() : deposit_;
      }
    }
    /**
     * <code>.wallet.Transaction deposit = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.isuru.wallet.service.Transaction, com.isuru.wallet.service.Transaction.Builder, com.isuru.wallet.service.TransactionOrBuilder> 
        getDepositFieldBuilder() {
      if (depositBuilder_ == null) {
        depositBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.isuru.wallet.service.Transaction, com.isuru.wallet.service.Transaction.Builder, com.isuru.wallet.service.TransactionOrBuilder>(
                getDeposit(),
                getParentForChildren(),
                isClean());
        deposit_ = null;
      }
      return depositBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.DepositRequest)
  }

  // @@protoc_insertion_point(class_scope:wallet.DepositRequest)
  private static final com.isuru.wallet.service.DepositRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.isuru.wallet.service.DepositRequest();
  }

  public static com.isuru.wallet.service.DepositRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DepositRequest>
      PARSER = new com.google.protobuf.AbstractParser<DepositRequest>() {
    public DepositRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DepositRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DepositRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DepositRequest> getParserForType() {
    return PARSER;
  }

  public com.isuru.wallet.service.DepositRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

