// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet.proto

package com.isuru.wallet.service;

public final class Wallet {
  private Wallet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_DepositRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_DepositRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_WithdrawalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_WithdrawalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_BalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_BalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_BalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_BalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_AccountBalance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_AccountBalance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023wallet/wallet.proto\022\006wallet\"6\n\016Deposit" +
      "Request\022$\n\007deposit\030\001 \001(\0132\023.wallet.Transa" +
      "ction\"<\n\021WithdrawalRequest\022\'\n\nwithdrawal" +
      "\030\001 \001(\0132\023.wallet.Transaction\"!\n\016BalanceRe" +
      "quest\022\017\n\007user_id\030\001 \001(\005\"A\n\017BalanceRespons" +
      "e\022.\n\016accountBalance\030\001 \003(\0132\026.wallet.Accou" +
      "ntBalance\"\206\001\n\013Transaction\022\017\n\007user_id\030\001 \001" +
      "(\005\022\016\n\006amount\030\002 \001(\001\022&\n\010currency\030\003 \001(\0162\024.w" +
      "allet.CurrencyType\".\n\017TransactionType\022\013\n" +
      "\007DEPOSIT\020\000\022\016\n\nWITHDRAWAL\020\001\"\202\001\n\016AccountBa" +
      "lance\022\017\n\007user_id\030\001 \001(\005\022\022\n\naccount_id\030\002 \001" +
      "(\005\022\022\n\nuser_email\030\003 \001(\t\022\017\n\007balance\030\004 \001(\001\022" +
      "&\n\010currency\030\005 \001(\0162\024.wallet.CurrencyType\"" +
      "&\n\023TransactionResponse\022\017\n\007message\030\001 \001(\t*" +
      ")\n\014CurrencyType\022\007\n\003EUR\020\000\022\007\n\003USD\020\001\022\007\n\003GBP" +
      "\020\0022\330\001\n\rWalletService\022@\n\007Deposit\022\026.wallet" +
      ".DepositRequest\032\033.wallet.TransactionResp" +
      "onse\"\000\022D\n\010Withdraw\022\031.wallet.WithdrawalRe" +
      "quest\032\033.wallet.TransactionResponse\"\000\022?\n\n" +
      "GetBalance\022\026.wallet.BalanceRequest\032\027.wal" +
      "let.BalanceResponse\"\000B\034\n\030com.isuru.walle" +
      "t.serviceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wallet_DepositRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wallet_DepositRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_DepositRequest_descriptor,
        new java.lang.String[] { "Deposit", });
    internal_static_wallet_WithdrawalRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wallet_WithdrawalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_WithdrawalRequest_descriptor,
        new java.lang.String[] { "Withdrawal", });
    internal_static_wallet_BalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wallet_BalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_BalanceRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_wallet_BalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_wallet_BalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_BalanceResponse_descriptor,
        new java.lang.String[] { "AccountBalance", });
    internal_static_wallet_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_wallet_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_Transaction_descriptor,
        new java.lang.String[] { "UserId", "Amount", "Currency", });
    internal_static_wallet_AccountBalance_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_wallet_AccountBalance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_AccountBalance_descriptor,
        new java.lang.String[] { "UserId", "AccountId", "UserEmail", "Balance", "Currency", });
    internal_static_wallet_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_wallet_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_TransactionResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
