// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet.proto

package com.isuru.wallet.service;

public interface WithdrawalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.WithdrawalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.wallet.Transaction withdrawal = 1;</code>
   */
  boolean hasWithdrawal();
  /**
   * <code>.wallet.Transaction withdrawal = 1;</code>
   */
  com.isuru.wallet.service.Transaction getWithdrawal();
  /**
   * <code>.wallet.Transaction withdrawal = 1;</code>
   */
  com.isuru.wallet.service.TransactionOrBuilder getWithdrawalOrBuilder();
}
